[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"

remappings = [
    '@v4-core/=lib/v4-core',
    '@openzeppelin=lib/openzeppelin-contracts/contracts',

    'forge-std/=lib/forge-std/src',
]

fs_permissions = [
  { access='read-write', path='./artifacts' },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
